data:
  train_bs: 1
  validation_bs: 1
  train_width: 256
  train_height: 256
  train_val_max_img: 2
  validation_val_max_img: 6
#   meta_paths:
#     - "./data/fashion_meta.json"
#   # Margin of frame indexes between ref and tgt images
#   sample_margin: 30  

train_data:
  target: src.dataset.ChDataset_GaussianSkeleton_DiverseAppearance_json_OpenPose.ChDataset
  params:
    json_path: /mnt/localssd/fox/fox_train.json
    target_joints: ['13','12','10','9','8','7','6','5','4','3','2','1','0']
    seed: 42
    dataset_size: 200
    mod: 2
    sample_n_frames: 0
    sample_size:     256
    sample_stride:   1
    n_pairs: 0
    flip_prob: 0.
    resize_prob: 0.
    composite_by_add: False
    everywhere_cartoon_prob: 0
    color_aug_prob: 0
    change_composite_order_prob: 0
    skeleton_layer_order: False
    rotate_translate_prob: 0.5

    draw_joint_skeleton: "openpose"
    bone_std: 4 #half
    joint_std: 4 #radius
    target_bg_color: "black"
    skeleton_bg_color: "black"

validation_data:
  # target: animatediff.data.DiverseTopo.ChDataset
  target: src.dataset.ChDataset_GaussianSkeleton_DiverseAppearance_json_OpenPose.ChDataset
  params:
    json_path: /mnt/localssd/fox/fox_test.json
    target_joints: ['13','12','10','9','8','7','6','5','4','3','2','1','0']
    seed: 42
    # dataset_size: 200
    # mod: 6
    sample_n_frames: 0
    sample_size:     256
    sample_stride:   1
    n_pairs: 0
    flip_prob: 0.
    resize_prob: 0.
    composite_by_add: False
    everywhere_cartoon_prob: 0
    color_aug_prob: 0
    change_composite_order_prob: 0
    skeleton_layer_order: False
    rotate_translate_prob: 0.

    draw_joint_skeleton: "openpose"
    bone_std: 4 #half
    joint_std: 4 #radius
    target_bg_color: "black"
    skeleton_bg_color: "black"


solver:
  gradient_accumulation_steps: 1
  mixed_precision: 'fp16'
  enable_xformers_memory_efficient_attention: True 
  gradient_checkpointing: False 
  max_train_steps: 30000
  max_grad_norm: 1.0
  # lr
  learning_rate: 1.0e-5
  scale_lr: False 
  lr_warmup_steps: 1
  lr_scheduler: 'constant'

  # optimizer
  use_8bit_adam: True
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay:  1.0e-2
  adam_epsilon: 1.0e-8

val:
  validation_steps: 500


noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "scaled_linear"
  steps_offset:        1
  clip_sample:         false

# base_model_path: './pretrained_weights/sd-image-variations-diffusers'
# vae_model_path: './pretrained_weights/sd-vae-ft-mse'
# image_encoder_path: './pretrained_weights/sd-image-variations-diffusers/image_encoder'
# controlnet_openpose_path: './pretrained_weights/control_v11p_sd15_openpose/diffusion_pytorch_model.bin'

base_model_path: "./pretrained_weights/stable-diffusion-v1-5/"
vae_model_path: "./pretrained_weights/sd-vae-ft-mse"
image_encoder_path: "./pretrained_weights/image_encoder"
denoising_unet_path: "./pretrained_weights/denoising_unet.pth"
reference_unet_path: "./pretrained_weights/reference_unet.pth"
pose_guider_path: "./pretrained_weights/pose_guider.pth"
# motion_module_path: "./pretrained_weights/motion_module.pth"


weight_dtype: 'fp16'  # [fp16, fp32]
uncond_ratio: 0.1
noise_offset: 0.05
snr_gamma: 5.0
enable_zero_snr: True 
pose_guider_pretrain: False #True 
# train_batch_size: 2

seed: 12580
resume_from_checkpoint: ''
checkpointing_steps: 500
save_model_epoch_interval: 5
exp_name: 'stage1'
output_dir: './results/finetune_openpose_json_fox'